trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - 'v*'
pr:
  branches:
    include:
      - '*'  # must quote since "*" is a YAML reserved character; we want a string
variables:
  CIBW_BUILDING: "true"
  CIBW_SKIP: "cp27-* cp34-* cp35-* pp27-* pp36-* pp37-*"
  CIBW_TEST_REQUIRES: "pytest pytest-sugar meshio pillow"
  CIBW_TEST_COMMAND: "python -c \"import vispy; vispy.test()\""
  CIBW_BUILD_VERBOSITY: "2"
  CIBW_BEFORE_BUILD: "pip install -U numpy Cython jupyter ipywidgets"
  CIBW_BEFORE_BUILD_MACOS: "npm install npm@latest -g; pip install -U pip setuptools"
  CIBW_BEFORE_BUILD_LINUX: "yum install -y fontconfig; pip install -U pip setuptools; pip install freetype-py"
  # If freetype-py is installed from source (no wheel found), include bundled freetype library
  CIBW_ENVIRONMENT_WINDOWS: "FREETYPEPY_BUNDLE_FT=1"
  CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
  CIBW_MANYLINUX_I686_IMAGE: manylinux2014
jobs:
- job: linux
  pool: {vmImage: 'Ubuntu-16.04'}
  steps:
    - task: UsePythonVersion@0
    - bash: |
        git submodule update --init --recursive
        python -m pip install --upgrade pip
        pip install cibuildwheel twine numpy Cython jupyter ipywidgets
        python setup.py sdist -d wheelhouse
        cibuildwheel --output-dir wheelhouse .
    - task: PublishPipelineArtifact@1
      inputs:
        path: $(System.DefaultWorkingDirectory)/wheelhouse
        artifact: vispyDeployLinux
- job: macos
  pool: {vmImage: 'macOS-10.14'}
  steps:
    - task: UsePythonVersion@0
    - bash: |
        git submodule update --init --recursive
        python -m pip install --upgrade pip
        pip install cibuildwheel
        cibuildwheel --output-dir wheelhouse .
    - task: PublishPipelineArtifact@1
      inputs:
        path: $(System.DefaultWorkingDirectory)/wheelhouse
        artifact: vispyDeployMacOS
- job: macos_10_14
  pool: {vmImage: 'macOS-10.14'}
  steps:
    - task: UsePythonVersion@0
    - bash: |
        git submodule update --init --recursive
        python -m pip install --upgrade pip
        pip install cibuildwheel
        MACOSX_DEPLOYMENT_TARGET="10.14" cibuildwheel --output-dir wheelhouse .
    - task: PublishPipelineArtifact@1
      inputs:
        path: $(System.DefaultWorkingDirectory)/wheelhouse
        artifact: vispyDeployMacOS_10_14
- job: windows
  pool: {vmImage: 'vs2017-win2016'}
  steps:
    - task: UsePythonVersion@0
    - bash: |
        git submodule update --init --recursive
        python -m pip install --upgrade pip
        pip install cibuildwheel
        cibuildwheel --output-dir wheelhouse .
    - task: PublishPipelineArtifact@1
      inputs:
        path: $(System.DefaultWorkingDirectory)/wheelhouse
        artifact: vispyDeployWindows
- job: deployPyPI
  pool: {vmImage: 'Ubuntu-16.04'}
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
  dependsOn:
    - linux
    - macos
    - macos_10_14
    - windows
  steps:
    - task: UsePythonVersion@0
    - task: DownloadPipelineArtifact@2
      inputs:
        patterns: |
          vispyDeployLinux/*
          vispyDeployMacOS/*.whl
          vispyDeployWindows/*.whl
          vispyDeployMacOS_10_14/*.whl
    - bash: |
        cd $(Pipeline.Workspace)
        python -m pip install --upgrade pip
        pip install twine
        twine upload -u "__token__" --skip-existing vispyDeployLinux/* vispyDeployMacOS/* vispyDeployWindows/*
      env:
        TWINE_PASSWORD: $(pypiToken2)
